### ISSUE TITLE
Getting invalid scope error

### ISSUE THREAD

**Issue by windians** [oktadeveloper/okta-angular-openid-connect-example#6]
I am following the tutorial posted on https://developer.okta.com/blog/2017/04/17/angular-authentication-with-oidc . I followed all the steps all the way to where we click the Login button and sign-in with one of the people that’s configured in our Okta application. I am getting an error  when I click on "Login" button. It changes the link on address bar to **http://localhost:4200/home#state=wgwMkOVYzOCdbMHD6D2QtuMMHjcDhhHQv7Xl9qrp&error=invalid_scope&error_description=One+or+more+scopes+are+not+configured+for+the+authorization+server+resource.** 
And on console it logs the following : 
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'nonceStateSeparator' of null
TypeError: Cannot read property 'nonceStateSeparator' of null
    at OAuthService.push../node_modules/angular-oauth2-oidc/esm5/angular-oauth2-oidc.js.OAuthService.tryLogin
```
By looking at the error I thought something might be wrong with how I am setting up oauthService in app.component. But everything looks ok to me over there as well. Below is copy of my app.component ts file. 
```
import { Component } from '@angular/core';
import { OAuthService, JwksValidationHandler } from 'angular-oauth2-oidc';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  constructor(private oauthService: OAuthService) {
    this.oauthService.redirectUri = window.location.origin;
    this.oauthService.clientId = '0oafim33hmykBg49e0n9';
    this.oauthService.scope = 'myemail@gmail.com';
    this.oauthService.issuer = 'https://dev-548729.oktapreview.com/oauth2/default';
    this.oauthService.tokenValidationHandler = new JwksValidationHandler();

    // Load Discovery Document and then try to login the user
    this.oauthService.loadDiscoveryDocumentAndTryLogin();
  }

}
 
```

Can someone tell me what might be going on ? I am very new to this.

**Comment by mraible** [comment]
The scope should be the following:

```
this.oauthService.scope = 'openid profile email';
```

Can you try changing to that and see if it works for you?

**Comment by windians** [comment]
Thanks for the prompt response Matt. After doing your change when I click on Login button I actually get redirected to Okta login page. But when I click sign in and go back into my Angular application I dont see the expected results. It doesn't pull my name back and also Login button  text does not change to Logout as it should according to the tutorial.

I also get the same message on console which I was getting earlier. 
```
core.js:1542 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'nonceStateSeparator' of null
TypeError: Cannot read property 'nonceStateSeparator' of null
    at OAuthService.push../node_modules/angular-oauth2-oidc/esm5/angular-oauth2-oidc.js.OAuthService.tryLogin (angular-oauth2-oidc.js:1068)
    at angular-oauth2-oidc.js:294
```

this is how my auth.guard.service ts look like:
```
import { Injectable } from '@angular/core';
import { ActivatedRouteSnapshot, CanActivate, Router, RouterStateSnapshot } from '@angular/router';
import { OAuthService } from 'angular-oauth2-oidc';

@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

  constructor(private oauthService: OAuthService, private router: Router) {}

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
    if (this.oauthService.hasValidIdToken()) {
      return true;
    }

    this.router.navigate(['/home']);
    return false;
  }
}
```
And this is how my home component looks like
```
import { Component } from '@angular/core';
import { OAuthService } from 'angular-oauth2-oidc';

@Component({
  template: `
    <div *ngIf="givenName">
      <h2>Welcome, {{givenName}}!</h2>
      <button (click)="logout()">Logout</button>
      <p><a routerLink="/search" routerLinkActive="active">Search</a></p>
    </div>

    <div *ngIf="!givenName">
      <button (click)="login()">Login</button>
    </div>`
})
export class HomeComponent {

  constructor(private oauthService: OAuthService) {
  }

  login() {
    this.oauthService.initImplicitFlow();
  }

  logout() {
    this.oauthService.logOut();
  }

  get givenName() {
    const claims = this.oauthService.getIdentityClaims();
    if (!claims) {
      return null;
    }
    return claims['name'];
  }
}
```

**Comment by mraible** [comment]
What version of angular-oauth2-oidc are you using? I’ve only tested with v3.1.4.

**Comment by windians** [comment]
I am using  "angular-oauth2-oidc": "^4.0.2" version. I will try to go down that version and give it another try.

**Comment by windians** [comment]
Wow angular-oauth2-oidc version was the issue! After downgrading to 3.1.4 version it worked like we expected. Thanks for all your help!
